= Change log

== Unreleased

* use vimdiff as Git merge and diff tool
* add `~/.vimrc`
* add modified Agnoster prompt theme via Oh My Posh
* add `~/.profile` for all POSIX-compliant shells
* add `~/.bash_profile` and `~/.bashrc` startup scripts for Bash sessions
* Allow shell configuration overrides via `~/local.profile`, `~/local.bash_profile`, `~/local.bashrc`
* add `cd` aliases `..`, `...`, `....` and `.....`
* add `g` alias for `git`
* colorize `grep` output by default
* add `l`, `lf` and `ld` aliases for `ls`, and colorize output by default
* make `mkdir` recursive by default
* add `s` alias for `sudo`
* add Git aliases `aliases`, `amend`, `attribute`, `br`, `branches`, `cm`, `changed`, `changes`, `cl`, `co`, `configure`, `contrib`, `current`, `default`, `delete`, `discard`, `down`, `download`, `experiment`, `feature`, `fell`, `fetched`, `filelog`, `file-history`, `fix`, `fixup`, `fast-forward`|`ff`, `graph`, `history`, `k`, `last`, `maint`, `orphan`, `orphan-fresh`, `pick`, `recent`, `refactor`, `remotes`, `reword`, `state`, `squash`, `staged`, `stashed`, `sw`, `sync`, `tags`, `track`, `tracking`, `unamend`, `uncommit`, `undo`, `unstage`, `untrack`, `up`, `up-force`, `upstream`, `versions` and `wip`
* allow Git configuration overrides via (`~/local.gitconfig`)
* add global Git excludes file (`~/local.gitignore`)
* record explicit merges by default (`--no-ff`)
* automatically prune refs to non-existent upstream branches and tags on `git fetch`
* rebase by default on `git pull`
* push tags by default with `git push`
* automatically setup remote branch tracking
* track branches of the same name by default
* set default branch name to "dev" on `git init`
* apply `--autosquash` rules automatically on rebase operations
* opt-out of security checks for Git repositories on external storage (`safe.directory`)
* add `lazygit` binary for Windows
* add `oh-my-posh` binary for Windows
