# ==============================================================================
# tmux config.
#
# https://github.com/tmux/tmux/wiki
# ==============================================================================

# By default, tmux uses `Ctrl-b` as the prefix key. However, many users find it
# awkward. `Ctrl-a` is a common, more accessible, alternative. This snippet
# remaps the prefix key to from 'Ctrl-b' to 'Ctrl-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# The default pane-splitting commands (`"` for vertical and `%` for horizontal)
# can be hard to remember. Use use more intuitive characters, `|` and `-`:
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Start window numbering at 1.
set -g base-index 1

# Easily reload the configuration file with `Ctrl-a r`:
bind r source-file ~/.tmux.conf
