# ==============================================================================
# tmux config.
#
# https://github.com/tmux/tmux/wiki
# ==============================================================================

# By default, tmux uses `C-b` (Ctrl-b) as the prefix key. However, many users
# find this key combination awkward. `Ctrl-a` is a common, more accessible,
# alternative, but it may conflict with other operations in some terminals
# and shells. The following configuration remaps the prefix key to from 'Ctrl-b'
# to 'Ctrl-a'.
#unbind C-b
#set-option -g prefix C-a
#bind-key C-a send-prefix

# The default pane-splitting commands (`"` for vertical and `%` for horizontal)
# can be hard to remember. The following configuration swaps those for more
# intuitive characters, `|` and `-` respectively.
#bind | split-window -h
#bind - split-window -v
#unbind '"'
#unbind %

# Use Alt+arrow keys, without the prefix key combination, to switch between
# panes. This is the key combination used in Terminator, a popular Linux
# terminal emulator with built-in multiplexing. You can't therefore use this key
# configuration with Terminator or any other terminal that uses the same keys.
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse support. This makes it easier to copy text from the tmux UI.
set -g mouse on

# Start window numbering at 1.
set -g base-index 1

# Enable some Vim keybindings. This enables, for example, the use of H, J, K and
# L to move the cursor left, down, up and right while in copy mode.
setw -g mode-keys vi

# When you have multiple tmux windows open, the following settings will show a
# visual notification in the status line when activity is detected in another
# window, and highlights the window with the activity.
setw -g monitor-activity on
set -g visual-activity on

# Easily reload the configuration file with `Ctrl-b r`:
bind r source-file ~/.tmux.conf

# Type `Ctrl-b D` (ie Shift-d) to load the `dev` script that automates the
# creation of my typical dev pane layout.
bind D source-file ~/.tmux/dev
