= Shell startup scripts

A shell environment can be interactive or non-interactive.

An *interactive shell* reads and writes to a user's terminal and may operate in login or non-login mode. An *interactive login shell* is typically spawned when a user enters a remote shell environment via SSH. Temporary *interactive non-login shells* are used to run scripts from the terminal and are invoked by the `sh` command (or `bash` etc).

Confusingly, different terminal programs launch _local_ shell environments in login or non-login mode. Windows Terminal, for example, runs shells in interactive login mode. But other terminals spawn shell environments in non-login mode by default. You can check which mode a shell is running in by typing:

[source]
----
shopt login_shell
----

A *non-interactive shell* is not associated with a user interface (terminal).

Various scripts are automatically executed by shells at startup. Which scripts are executed depends on the mode in which the shell is running.

Interactive login shells look for a file called `/etc/profile` and, if the file exists and is readable, executes the script's commands. Then the same happens for the user-level `~/.profile` file. These scripts are loaded automatically by all shells – Bash, Fish, Zsh, etc – at startup of a new _interactive login_ session.

Different shells extend the standard startup behaviors with their own proprietary conventions. For example, Bash will attempt to execute `~/.bash_profile`, `~/.bash_login` or `~/.profile` – the first one it finds, in that order – when started in interactive login mode. The `~/.bash_profile` file, if it exists, takes precedence over `~/.profile`

Bash reads a file called `~/.bashrc` ("Bash run command"), if it exists, whenever a new Bash shell is spawned, regardless of the mode in which the shell is running.

As a general rule, `~/.bash_profile` should be used to set environment variables and to run commands that need to be run only once per login session, while `~/.bashrc` should be used to do things every time Bash is run, regardless of the mode in which it operates. The `~/.bashrc` file is a good place to define aliases and functions, and to customize the prompt and history.

It is common practice to include a command in `~/.bash_profile` to source `~/.bashrc`, so that the same configuration is applied regardless of the mode in which the shell is running. This ensures a higher degree of consistency between terminal programs, which spawn shells in different modes.

```sh
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi
```

== What `bin/update!` does

The `bin/update!` script for these dotfiles will install a symlinked `~/.profile` file in your home directory. This is used to set some global environment variables (which will be inherited by all subshells). The `~/.profile` script is also used to load POSIX-compliant, shell-agnostic aliases and functions, as well as a suite of other utilities that will be useful in every interactive shell environment.

The `bin/update!` script also installs a symlinked `~/.bash_profile` file in your home directory. This includes a command to source the `~/.profile` script, thus Bash terminal environments will inherit the POSIX-compliant, shell-agnostic configuration defined in `~/.profile`. And, as per common practice, the `~/.bash_profile` file also sources `~/.bashrc`, so ensuring consistent behavior regardless of the mode in which terminal programs run Bash by default.

In general, the `~/.bash_profile` is not used because it will not be run in all local Bash shell instances (depending on the terminal program being used), while `~/.bashrc` is used to define local environment variables, aliases and functions, and to customize the prompt and history. Both scripts depend on Bash-specific syntax and APIs.

The `bin/update!` script also installs "local" versions of all these files into your user directory:

- `local.profile`
- `local.bash_profile`
- `local.bashrc`

The idea is that you SHOULD NOT edit directly the "global" `~/.profile`, `~/.bash_profile` and `~/.bashrc` files, as the content of these files are managed via this repository. Instead, you MAY edit any of the "local" files with custom shell configurations specific to each local computing environment.

Whenever you update the "local" shell startup scripts you can call the `reload!` function to re-source the shell startup scripts, so your changes take effect immediately.

[source]
----
reload!
----
