= Requirements

The dotfiles and Git aliases are compatible with POSIX-compliant shell environments. On Windows, https://gitforwindows.org/[Git Bash] and Ubuntu running in WSL2 are both supported.

The following programs are REQUIRED:

* Git >= v2.35
* Delta

See instructions below for installing the correct version of Git.

https://github.com/dandavison/delta[Delta], is a paging utility. The Git configuration swaps `less` for `delta` for paging output from commands like `git log` and `git diff`. On Ubuntu/WSL, `git-delta` is bundled with the `git-extras` package and can therefore be installed using the following command:

[source]
----
sudo apt install git-extras
----

The following programs are OPTIONAL. See the links for installation instructions.

* link:https://github.com/jesseduffield/lazygit#installation[LazyGit]
* link:https://github.com/neovim/neovim/blob/master/INSTALL.md[Neovim]
* link:https://ohmyposh.dev/docs/installation/linux[Oh-My-Posh]

.Windows binaries
****
My link:https://github.com/kieranpotts/devtools[devtools] repository includes Windows binaries for `delta`, `lazygit`, `oh-my-posh`, and others. These can be enabled in Git Bash simply by appending that repository's `bin` directory to Windows' `PATH` environment variable. NeoVim needs to be installed manually on Windows.
****

== Git

The Git configuration has been tested with https://git-scm.com/[Git] v2.39.1 and is expected to be incompatible with versions after v2.35. For Debian distros, run the following command to check which is the current version of Git available via the APT package manager.

[source]
----
apt-cache policy git
----

If the available version is >= v2.35, go ahead and install from the default artifact registry.

[source]
----
sudo apt-get update
sudo apt-get install git -y
----

[TIP]
======
You can specify the specific version of a package to install using either of the following commands.

[source]
----
sudo apt-get install <package-name>=<package-version-number>
sudo apt-get -t=<target release> install <package-name>
----
======

Check the installed version with the command `git --version`.

If you want to install a newer version of Git than is available via the default package registries, use `wget` to download the version directly from the source. For example, to download the source for Git v2.35.0, run the following command.

[source]
----
wget https://github.com/git/git/archive/refs/tags/v2.35.0.tar.gz
----

Before extracting the package, install the following packages.

[source]
----
sudo apt-get update
sudo apt-get install libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc
----

Extract the Git package, then navigate to the extracted directory. (Path names may differ from the example below).

[source]
----
tar -zxf v2.35.0.tar.gz
cd git-2.35.0
----

Run the following command to build and install the package. This is a slow operation.

[source]
----
make prefix=/usr/local all
sudo make prefix=/usr/local install
----

Restart your terminal then check the installed Git version with the command `git --version`. Use `rm` to remove the temporary files and directories.

== Git LFS

Some of my other repositories use https://git-lfs.com/[Git Large File Storage]. This is a Git extension that removes large files from the repository and stores them elsewhere, cross-referenced from the Git repository using pointers.

To install Git LFS locally, first download and install the Git command line extension from the https://git-lfs.com/[Git LFS website]. Git LFS is available from the APT package manager – `sudo apt-get install git-lfs` – else see the https://github.com/git-lfs/git-lfs/blob/main/INSTALLING.md[installation instructions].

Then run the following command:

[source]
----
git lfs install
----

In each Git repository where you want to use Git LFS, run the following command to configure the file types that you'd like Git LFS to manage. Alternatively, you can edit the `.gitattributes` file directly (this file MUST be committed).

[source]
----
git lfs track "*.pdf"
----

Then commit and push as you normally would. To convert existing files previously committed to the repository use the `git lfs migrate` command. See the https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.adoc[documentation].

See also link:https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github[About large files on GitHub].
