name: Validation

on:
  - workflow_dispatch
  - push

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate commit message
        run: |
          git log --format=%s ORIG_HEAD..HEAD | while read -r line; do
            if [[ ! $line =~ ^constraint: [a-z].*$ && ! $line =~ ^experiment: [a-z].*$ && ! $line =~ ^feature: [a-z].*$ && ! $line =~ ^fix: [a-z].*$ && ! $line =~ ^maintenance: [a-z].*$ && ! $line =~ ^merge: [a-z].*$ && ! $line =~ ^refactor: [a-z].*$ ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done
