name: Validation

on:
  - workflow_dispatch
  - push

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate commit message
        run: |
          git log --format=%s ORIG_HEAD..HEAD | while read -r line; do
            echo "Validating commit message: $line"
            if [[ ! $line =~ ^((constraint|experiment|feature|fix|maintenance|merge|refactor): [a-z].*)$ ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done
