name: Validation

on:
  - push

jobs:
  validate-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate commit message
        run: |
          # Equivalent to `git log ORIG_HEAD..HEAD --oneline`.
          # `github.event.before` is the last commit SHA before the push.
          git log ${{ github.event.before }}..${{ github.sha }} --oneline | while read -r line; do
            echo "Validating commit message: $line"
            if [[ ! $line =~ ^((constraint|experiment|feature|fix|maintenance|merge|refactor): [a-z].*)$ ]]; then
              echo "Invalid commit message: $line"
              exit 1
            fi
          done
